name: ollama

services:
  ollama-igpu:
    build:
      context: .
      dockerfile: Dockerfile.igpu
    container_name: ollama-igpu-container
    devices:
      - /dev/dri:/dev/dri
    # ollama models directory
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_DEBUG=1
      - ONEAPI_DEVICE_SELECTOR=level_zero:0
      - IPEX_LLM_NUM_CTX=16384
    restart: unless-stopped
